### ISSUE TITLE
Swiping to previous post is inconsistent

### ISSUE THREAD

**Issue by drcouzelis** [walokra/sailimgur#21]
When viewing an imgur post, I can place my finger on the center of the screen and swipe to the left, which will switch to the next post. But, swiping to the right has inconsistent results: sometimes it will switch to the previous post, and sometimes it will go back to main thumbnail gallery.

...Or maybe I'm just doing it wrong. ;) What is the method of switching to the previous post?

**Comment by walokra** [comment]
It works just like you're doing, swiping left or right from the image. But I've also noticed that after some Sailfish OS update swiping left goes more easily to main gallery than previous post. 

You can also navigate with the previous / next buttons at the bottom.

**Comment by drcouzelis** [comment]
Oh! I didn't realize there were buttons on the bottom! This resolves my issue.

Thank you for the excellent application! :)
