### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by ichthyosaurus** [walokra/sailimgur#22]
Are you still interested in this project?

I'd like to (sooner or later, currently probably rather later) merge the changes I made in my patch back upstream. The patch is available on OpenRepos.

If you're not interested in the project any more: would it be ok for you if I create a fork under same name? (Or a new name?)

**Comment by walokra** [comment]
This project is alive but isn't actively maintained as I don't currently have an Sailfish OS device (old Jolla device in the drawers though).

But having said that, pull requests and patches are welcome.

Could you point me to your openrepos patch or even better make a pull request to this repository?

I'll check my Sailfish OS development environment in the mean time.

**Comment by ichthyosaurus** [comment]
That is nice to hear :)!

My patch is available here: https://openrepos.net/content/ichthyosaurus/patch-various-changes-harbour-sailimgur

It's not very nice code though, and I wanted to cleanly rewrite it before creating a PR. I'm still planning on doing that soon:tm:, when I finally find some free time to catch up on all my projects.

**Comment by walokra** [comment]
Thanks for the patch, I managed to apply it and quickly test it with anonymous user.

Nice refactoring on some parts and simplifying the code. I'll do some more testing when I've more time and create a new version with the changes.

**Comment by ichthyosaurus** [comment]
There's one bug that I'm aware of: after downloading an image from a gallery, the download buttons of all currently shown images switch to "downloaded" mode. I'm not sure anymore why this was the case. I *think* it would have needed a change on the C++ side to make the signal more specific.

**Comment by ichthyosaurus** [comment]
It also closes #18.

**Comment by walokra** [comment]
The changes have now been merged (excluding image details part and changing the download icon). New version has been released to OpenRepos and to Jolla Store.
