### ISSUE TITLE
aarch64 build?

### ISSUE THREAD

**Issue by poetaster** [walokra/sailimgur#25]
I can also help getting the app into chum (build.sailfishfishos.org) for automagical builds?

Thanks!

**Comment by poetaster** [comment]
I took the liberty of putting it up on build. ... it pulls one the 0.10.0 release tag. If you like I can get it promoted to chum. Then everyone can just install.

**Comment by walokra** [comment]
Thanks for the iniative. 

Sailimgur is already on OBS https://build.sailfishos.org/package/show/home:walokra:sailfishos/sailimgur but as noted it lacks the aarch64 build. I will check how I get the architechture to build (OBS isn't the user friendliest service) and promote it.

**Comment by walokra** [comment]
Sailimgur is now available on https://build.sailfishos.org/package/show/sailfishos:chum:testing/sailimgur

**Comment by poetaster** [comment]
thanks! saw you've got the others in the pipeline.
