### ISSUE TITLE
Swiping to go to next image does not work

### ISSUE THREAD

**Issue by henk84** [walokra/sailimgur#27]
Hi

You may remember me from #26: I’m using sailimgur on aarch64.
I noticed an issue compared to the version I used on the jolla1/armv7hl:
Swiping from the right on an image to go to the next post does not work anymore, there is simply no reaction at all.
That means I always have to get my thumb to the lower right corner of the display (one-hand user) which is a lot less comfortable with either hand IMHO.
Could you please look into why that’s not working anymore?
Let me know if there is any other info I can provide to help solve this.

Thank you very much

henk

**Comment by walokra** [comment]
The swipe was missing mousearea from earlier code changes.
