### ISSUE TITLE
Animations (videos, gifs, etc?) behaviour

### ISSUE THREAD

**Issue by henk84** [walokra/sailimgur#28]
Hi

There is one issue that I find slightly inconvenient:
most (>90% I’d estimate) animated posts (gifs and/or videos) are not being played, or are being played without picture, i.e. sound only.
One example from the current frontpage is https://imgur.com/a/vprZgRn which might be an mp4.
The placeholder icon (white 'play' symbol in a dark grey circle) just sits there and has the 'loading' indicator spinning around it.
I tried "open in external browser" and there it plays fine, both video and audio.

Another example is https://imgur.com/a/fL6N6HC which seems also to be an mp4.
The loading indicator around the placeholder eventually stops spinning but when I press play I only get to hear the audio, video stays blank.
This also works fine in external browser.

I found an animation that works https://imgur.com/a/vdNkFTB and it’s without sound.
The placeholder loads and disappears to show the beginning of the video with a play button on it. I can then start the video and watch it (but not stop it, that’s probably worth a different ticket, though).
According to my desktop firefox’ page information it’s also an mp4. Or at least the file extension is …

Do you have any idea what might be the cause for this?
Might I be missing any codecs maybe?
Could the setting "Use video player" be relevant? Would you recommend setting it to on or off? I don’t really understand the difference between the two, could you elaborate a bit?

Thank you very much

henk

**Comment by walokra** [comment]
Using image component for video thumbnail didn't work anymore which caused problems. Changed to using real thumbnail. 

Also using video player is now always required for videos (animated content if not gif) and it has been set on by default before.
