### ISSUE TITLE
Feature Request: display link

### ISSUE THREAD

**Issue by henk84** [walokra/sailimgur#30]
Hi

due to #28 I sometimes want to see the link to navigate to that post in my desktop computer’s browser.
On my jolla1 I had three browsers installed (official, webcat, webpirate) and choosing "open in external browser" from the pulley menu would display the link when asking me which browser to use. On the new phone that does not happen so it’s not a good workaround anymore.
The option "copy link to clipboard" shows the link only very shortly but that sometimes was already enough. On my new phone there is a notch for the camera at the top which covers the post id, though, so I can’t use that to get the link at all.

So my request is to add an option "show link" that just displays the link of the currently viewed post anywhere on screen (not on the top, though, because of the camera notch) for me to type it off.
Do you think you could implement that?

Thank you very much

henk

**Comment by walokra** [comment]
Added gallery link to be shown below images.
